server:
  port: 8081
spring:
  application:
    name: mcp-server
  main:
    banner-mode: off
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-sk-******
      chat:
        options:
          model: deepseek-chat
    mcp:
      server:
        name: mcp-server
        version: 1.0.0