server:
  port: 8081
spring:
  profiles:
    active: mysql

mybatis-plus:
  mapper-locations: classpath:mybatis/xml/Common.xml,classpath:mybatis/custom/**/*.xml
  typeAliasesPackage: com.bulain.mybatis.*.model
  global-config:
    db-config:
      id-type: assign_id
      capital-mode: false
      table-underline: true
      update-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

logging:
  level:
    root: WARN
    org.springframework: INFO
    com.bulain: DEBUG

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_dev
    username: mybatis
    password: mybatis
  redis:
    host: 127.0.0.1
    port: 6379
    password: dev
  flyway:
    locations: classpath:/migration/mysql/
    baseline-on-migrate: true
---
spring:
  config:
    activate:
      on-profile: dm
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236?comOracle=true
    username: mybatis
    password: mybatis@123
  redis:
    host: 127.0.0.1
    port: 6379
    password: dev
  flyway:
    locations: classpath:/migration/dm/
    baseline-on-migrate: true
