server:
  port: 8082
spring:
  profiles:
    active: mysql
  main:
    banner-mode: off

mybatis-plus:
  mapper-locations: classpath:mybatis/xml/Common.xml,classpath:mybatis/custom/**/*.xml
  typeAliasesPackage: com.bulain.mybatis.*.model
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      capital-mode: false
      table-underline: true
      update-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

seata:
  application-id: mybatis-demo
  tx-service-group: default_tx_group
  enabled: true
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: nacos
      password: nacos
      context-path:
      data-id: client.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: nacos
      password: nacos
      context-path:

logging:
  level:
    root: WARN
    org.springframework: INFO
    com.bulain: DEBUG

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mybatis_dev?useSSL=false&autoReconnect=true&serverTimezone=PRC&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: mybatis
    password: mybatis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: dev
  flyway:
    locations: classpath:/migration/mysql/
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521/xepdb1
    username: mybatis_dev
    password: mybatis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: dev
  flyway:
    locations: classpath:/migration/oracle/
    baseline-on-migrate: true
mybatis-plus:
  configuration:
    variables:
      db-type: oracle12c
---
spring:
  config:
    activate:
      on-profile: dm
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236?comOracle=true
    username: mybatis
    password: mybatis@123
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: dev
  flyway:
    locations: classpath:/migration/dm/
    baseline-on-migrate: true