server:
  port: 8109
spring:
  application:
    name: mime-demo
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    root: INFO
  file:
    name: logs/mime-demo.log
    max-size: 100MB
    max-history: 7