spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_dev
    username: mybatis
    password: mybatis
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  mapper-locations: classpath:mybatis/xml/Common.xml,classpath:mybatis/custom/**/*.xml
  typeAliasesPackage: com.bulain.mybatis.*.model
  global-config:
    db-config:
      id-type: assign_id
      capital-mode: false
      table-underline: true
      update-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    jdbc-type-for-null: 'null'
