server: 
   servlet:
      session: 
         tracking-modes: cookie
   tomcat:
      uri-encoding: UTF-8
      
management:
   security:
      enabled: false
      
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis_dev
      username: mybatis
      password: mybatis
   mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp

#logging.level.org.springframework.security: DEBUG