-- // create table demo_order
-- Migration SQL that makes the change goes here.
CREATE TABLE DEMO_ORDER
(
    ID           VARCHAR2(20) NOT NULL,

    ORDER_NO     VARCHAR2(50) NOT NULL,
    EXTN_REF_NO1 VARCHAR2(50),
    EXTN_REF_NO2 VARCHAR2(50),
    EXTN_REF_NO3 VARCHAR2(50),

    CREATED_VIA  VARCHAR2(50),
    REMARKS      VARCHAR2(500),
    CREATED_AT   DATE,
    CREATED_BY   VARCHAR2(50),
    UPDATED_AT   DATE,
    UPDATED_BY   VARCHAR2(50),
    VERSION      NUMBER(20)   DEFAULT 0,
    DELETED      NUMBER(10)   DEFAULT 0,
    ARCHIVED     CHAR(1),

    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_DEMO_ORDER_1 ON DEMO_ORDER (ORDER_NO);

